### ISSUE TITLE
TODO: docker and centos packaging

### ISSUE THREAD

**Issue by Chilledheart** [Chilledheart/yass#13]
docker build is straightforward, the example Dockerfile should be like below:
```
FROM centos:8

# Install requirements : update repo
RUN yum update -y && \
    yum install -y dnf-plugins-core epel-release && \
    dnf config-manager --set-enabled powertools && \
    yum install -y gcc gcc-c++ make python bash coreutils diffutils patch && \
    yum install -y cmake ninja-build pkg-config perl golang && \
    yum install -y libunwind-devel, gtk3-devel, gtkmm30-devel && \
    yum clean all && \
    rm -rf /var/cache/yum

RUN ./scripts/build-rpm.sh  
```

However, we still need registery and github actions to upload and download built docker image. The action files should be like below:

```
jobs:
  docker_hub_publish:
    strategy:
      matrix:
        container:
        - 'centos8-build'

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: Chilledheart/docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: docker
        dockerfile: ${{ matrix.container }}
        cache: true
        tags: ${{ matrix.container }}
```
